Ext.define('Rfx.model.ProduceTable', {
    extend: 'Rfx.model.Base',
    fields: [ 
             'id',
             'class_name',
             'plan_date', 
             'regist_date', 
             'wa_name',
             'full_spec',
             'description',
             'specification',
             'gr_date_supplier',
             'pcs01',
             'pcs02',
             'pcs03',
             'pcs04',
             'pcs05',
             'pcs06',
             'pcs07',
             'pcs08',
             'pcs09',
             'pcs10',
             'pcs11',
             'pcs12',
             
             'pcs01name',
             'pcs02name',
             'pcs03name',
             'pcs04name',
             'pcs05name',
             'pcs06name',
             'pcs07name',
             'pcs08name',
             'pcs09name',
             'pcs10name',
             'pcs11name',
             'pcs12name',
             
             'pcs01sup',
             'pcs02sup',
             'pcs03sup',
             'pcs04sup',
             'pcs05sup',
             'pcs06sup',
             'pcs07sup',
             'pcs08sup',
             'pcs09sup',
             'pcs10sup',
             'pcs11sup',
             'pcs12sup',
             'qty',
             'spo_delivery',
             'supplier_name'
    ]
});